---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neumann

resources:
  - namespace.yaml
  - configmap.yaml
  - statefulset.yaml
  - service-headless.yaml
  - service-client.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
