---
apiVersion: v1
kind: Service
metadata:
  name: neumann-headless
  namespace: neumann
  labels:
    app.kubernetes.io/name: neumann
    app.kubernetes.io/component: headless
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: neumann
  ports:
    - name: grpc
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: raft
      port: 9300
      targetPort: 9300
      protocol: TCP
