---
apiVersion: v1
kind: Service
metadata:
  name: neumann
  namespace: neumann
  labels:
    app.kubernetes.io/name: neumann
    app.kubernetes.io/component: client
spec:
  type: ClusterIP
  selector:
    app: neumann
  ports:
    - name: grpc
      port: 9200
      targetPort: 9200
      protocol: TCP
