[workspace]
resolver = "2"
members = [
    "tensor_store",
    "relational_engine",
    "graph_engine",
    "vector_engine",
    "query_router",
    "neumann_parser",
    "neumann_shell",
    "tensor_compress",
    "tensor_vault",
]
