# Rust formatting configuration for Neumann
# https://rust-lang.github.io/rustfmt/

edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
reorder_imports = true
reorder_modules = true

# Match arms
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true

# Functions
fn_params_layout = "Tall"

# Other
use_field_init_shorthand = true
use_try_shorthand = true
